
---
events:
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:12 (find_program)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_UNAME"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "uname"
    candidate_directories:
      - "/Users/oghenemarho/.cargo/bin/"
      - "/Users/oghenemarho/.bun/bin/"
      - "/Users/oghenemarho/.pixi/bin/"
      - "/Users/oghenemarho/.deno/bin/"
      - "/opt/homebrew/opt/binutils/bin/"
      - "/Users/oghenemarho/.local/share/zinit/polaris/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/oghenemarho/.local/share/solana/install/active_release/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/opt/X11/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/oghenemarho/.dotnet/tools/"
      - "/usr/local/go/bin/"
      - "/Library/Frameworks/Mono.framework/Versions/Current/Commands/"
      - "/Users/oghenemarho/.platformio/penv/bin/"
      - "/usr/local/mysql-8.0.29-macos12-arm64/bin/"
      - "/Users/oghenemarho/Library/Android/sdk/emulator/"
      - "/Users/oghenemarho/Library/Android/sdk/platform-tools/"
      - "/Users/oghenemarho/.orbstack/bin/"
    searched_directories:
      - "/Users/oghenemarho/.cargo/bin/uname"
      - "/Users/oghenemarho/.bun/bin/uname"
      - "/Users/oghenemarho/.pixi/bin/uname"
      - "/Users/oghenemarho/.deno/bin/uname"
      - "/opt/homebrew/opt/binutils/bin/uname"
      - "/Users/oghenemarho/.local/share/zinit/polaris/bin/uname"
      - "/opt/homebrew/bin/uname"
      - "/opt/homebrew/sbin/uname"
      - "/Users/oghenemarho/.local/share/solana/install/active_release/bin/uname"
      - "/usr/local/bin/uname"
      - "/System/Cryptexes/App/usr/bin/uname"
    found: "/usr/bin/uname"
    search_context:
      ENV{PATH}:
        - "/Users/oghenemarho/.cargo/bin"
        - "/Users/oghenemarho/.bun/bin"
        - "/Users/oghenemarho/.pixi/bin"
        - "/Users/oghenemarho/.deno/bin"
        - "/opt/homebrew/opt/binutils/bin"
        - "/Users/oghenemarho/.local/share/zinit/polaris/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/oghenemarho/.local/share/solana/install/active_release/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/opt/X11/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/usr/local/go/bin"
        - "/Library/Frameworks/Mono.framework/Versions/Current/Commands"
        - "/Users/oghenemarho/.cargo/bin"
        - "/Users/oghenemarho/.platformio/penv/bin"
        - "/usr/local/mysql-8.0.29-macos12-arm64/bin"
        - "/Users/oghenemarho/Library/Android/sdk/emulator"
        - "/Users/oghenemarho/Library/Android/sdk/platform-tools"
        - "/Users/oghenemarho/.orbstack/bin"
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:212 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Darwin - 25.2.0 - arm64
  -
    kind: "find-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/Platform/Darwin.cmake:76 (find_program)"
      - "/opt/homebrew/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:32 (include)"
      - "CMakeLists.txt:16 (project)"
    mode: "program"
    variable: "CMAKE_INSTALL_NAME_TOOL"
    description: "Path to a program."
    settings:
      SearchFramework: "FIRST"
      SearchAppBundle: "FIRST"
      CMAKE_FIND_USE_CMAKE_PATH: true
      CMAKE_FIND_USE_CMAKE_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_SYSTEM_ENVIRONMENT_PATH: true
      CMAKE_FIND_USE_CMAKE_SYSTEM_PATH: true
      CMAKE_FIND_USE_INSTALL_PREFIX: true
    names:
      - "install_name_tool"
    candidate_directories:
      - "/Users/oghenemarho/.cargo/bin/"
      - "/Users/oghenemarho/.bun/bin/"
      - "/Users/oghenemarho/.pixi/bin/"
      - "/Users/oghenemarho/.deno/bin/"
      - "/opt/homebrew/opt/binutils/bin/"
      - "/Users/oghenemarho/.local/share/zinit/polaris/bin/"
      - "/opt/homebrew/bin/"
      - "/opt/homebrew/sbin/"
      - "/Users/oghenemarho/.local/share/solana/install/active_release/bin/"
      - "/usr/local/bin/"
      - "/System/Cryptexes/App/usr/bin/"
      - "/usr/bin/"
      - "/bin/"
      - "/usr/sbin/"
      - "/sbin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin/"
      - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin/"
      - "/opt/pmk/env/global/bin/"
      - "/opt/X11/bin/"
      - "/Library/Apple/usr/bin/"
      - "/usr/local/share/dotnet/"
      - "/Users/oghenemarho/.dotnet/tools/"
      - "/usr/local/go/bin/"
      - "/Library/Frameworks/Mono.framework/Versions/Current/Commands/"
      - "/Users/oghenemarho/.platformio/penv/bin/"
      - "/usr/local/mysql-8.0.29-macos12-arm64/bin/"
      - "/Users/oghenemarho/Library/Android/sdk/emulator/"
      - "/Users/oghenemarho/Library/Android/sdk/platform-tools/"
      - "/Users/oghenemarho/.orbstack/bin/"
    searched_directories:
      - "/Users/oghenemarho/.cargo/bin/install_name_tool"
      - "/Users/oghenemarho/.bun/bin/install_name_tool"
      - "/Users/oghenemarho/.pixi/bin/install_name_tool"
      - "/Users/oghenemarho/.deno/bin/install_name_tool"
      - "/opt/homebrew/opt/binutils/bin/install_name_tool"
      - "/Users/oghenemarho/.local/share/zinit/polaris/bin/install_name_tool"
      - "/opt/homebrew/bin/install_name_tool"
      - "/opt/homebrew/sbin/install_name_tool"
      - "/Users/oghenemarho/.local/share/solana/install/active_release/bin/install_name_tool"
      - "/usr/local/bin/install_name_tool"
      - "/System/Cryptexes/App/usr/bin/install_name_tool"
    found: "/usr/bin/install_name_tool"
    search_context:
      ENV{PATH}:
        - "/Users/oghenemarho/.cargo/bin"
        - "/Users/oghenemarho/.bun/bin"
        - "/Users/oghenemarho/.pixi/bin"
        - "/Users/oghenemarho/.deno/bin"
        - "/opt/homebrew/opt/binutils/bin"
        - "/Users/oghenemarho/.local/share/zinit/polaris/bin"
        - "/opt/homebrew/bin"
        - "/opt/homebrew/sbin"
        - "/Users/oghenemarho/.local/share/solana/install/active_release/bin"
        - "/usr/local/bin"
        - "/System/Cryptexes/App/usr/bin"
        - "/usr/bin"
        - "/bin"
        - "/usr/sbin"
        - "/sbin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin"
        - "/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin"
        - "/opt/pmk/env/global/bin"
        - "/opt/X11/bin"
        - "/Library/Apple/usr/bin"
        - "/usr/local/share/dotnet"
        - "~/.dotnet/tools"
        - "/usr/local/go/bin"
        - "/Library/Frameworks/Mono.framework/Versions/Current/Commands"
        - "/Users/oghenemarho/.cargo/bin"
        - "/Users/oghenemarho/.platformio/penv/bin"
        - "/usr/local/mysql-8.0.29-macos12-arm64/bin"
        - "/Users/oghenemarho/Library/Android/sdk/emulator"
        - "/Users/oghenemarho/Library/Android/sdk/platform-tools"
        - "/Users/oghenemarho/.orbstack/bin"
      CMAKE_INSTALL_PREFIX: "/usr/local"
...
